import { GameObject, ObjectName } from '@common/interfaces/object';
import { Dice, Player, PlayerData } from '@common/interfaces/player';

export const mockPlayers: Player[] = [
    {
        id: 'player-1',
        name: 'RAMI',
        avatar: 'assets/images/homme2.png',
        movesLeft: 7,
        actionsLeft: 2,
        attributes: { currentHealth: 12, health: 75, attack: { value: 4, dice: Dice.Dice4 }, defense: { value: 4, dice: Dice.Dice6 }, speed: 16 },
        data: [PlayerData.Admin, PlayerData.Active, PlayerData.Combat],
        inventory: [{ name: ObjectName.Bone }, { name: ObjectName.Steak }] as GameObject[],
        stats: {
            victories: 2,
            defeats: 0,
            evasions: 3,
            combat: 5,
            lostHP: 42,
            damageDone: 87,
            nbrOfPickedUpObjects: 3,
            tilesVisitedPercentage: 15,
        },
        diceResult: 0,
    },
    {
        id: 'player-2',
        name: 'JORDAN',
        avatar: 'assets/images/homme2.png',
        movesLeft: 7,
        actionsLeft: 2,
        attributes: { currentHealth: 100, health: 100, attack: { value: 4, dice: Dice.Dice4 }, defense: { value: 4, dice: Dice.Dice6 }, speed: 7 },
        data: [PlayerData.Disconnected],
        inventory: [],
        stats: {
            victories: 1,
            defeats: 2,
            evasions: 1,
            combat: 3,
            lostHP: 65,
            damageDone: 45,
            nbrOfPickedUpObjects: 5,
            tilesVisitedPercentage: 12,
        },
        diceResult: 0,
    },
    {
        id: 'player-3',
        name: 'SEB',
        avatar: 'assets/images/homme2.png',
        movesLeft: 7,
        actionsLeft: 2,
        attributes: { currentHealth: 92, health: 92, attack: { value: 4, dice: Dice.Dice4 }, defense: { value: 4, dice: Dice.Dice6 }, speed: 4 },
        data: [PlayerData.Combat],
        inventory: [],
        stats: {
            victories: 2,
            defeats: 1,
            evasions: 2,
            combat: 4,
            lostHP: 38,
            damageDone: 72,
            nbrOfPickedUpObjects: 2,
            tilesVisitedPercentage: 18,
        },
        diceResult: 0,
    },
    {
        id: 'player-4',
        name: 'SARAH',
        avatar: 'assets/images/homme2.png',
        movesLeft: 17,
        actionsLeft: 2,
        attributes: { currentHealth: 95, health: 95, attack: { value: 4, dice: Dice.Dice4 }, defense: { value: 4, dice: Dice.Dice6 }, speed: 4 },
        data: [],
        inventory: [],
        stats: {
            victories: 2,
            defeats: 0,
            evasions: 4,
            combat: 6,
            lostHP: 28,
            damageDone: 93,
            nbrOfPickedUpObjects: 4,
            tilesVisitedPercentage: 20,
        },
        diceResult: 0,
    },
];
